apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecms.fullname" . }}-api
  labels:
    {{- include "ecms.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "ecms.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ toJson .Values.api.command }}
          envFrom:
            - configMapRef:
                name: {{ include "ecms.fullname" . }}-config
            - secretRef:
                name: {{ default (printf "%s-secret" (include "ecms.fullname" .)) .Values.secret.existingSecret }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/v1
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
