{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecms.fullname" . }}-worker
  labels:
    {{- include "ecms.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "ecms.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ toJson .Values.worker.command }}
          envFrom:
            - configMapRef:
                name: {{ include "ecms.fullname" . }}-config
            - secretRef:
                name: {{ default (printf "%s-secret" (include "ecms.fullname" .)) .Values.secret.existingSecret }}
          env:
            - name: WORKER_QUEUE
              value: {{ .Values.worker.queueName | quote }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
{{- end }}
