{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecms.fullname" . }}-secret
  labels:
    {{- include "ecms.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.data.DATABASE_URL | quote }}
  JWT_SECRET: {{ .Values.secret.data.JWT_SECRET | quote }}
  REDIS_PASSWORD: {{ .Values.secret.data.REDIS_PASSWORD | quote }}
  RABBITMQ_URL: {{ .Values.secret.data.RABBITMQ_URL | quote }}
  MONGODB_URI: {{ .Values.secret.data.MONGODB_URI | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.data.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.data.AWS_SECRET_ACCESS_KEY | quote }}
  AWS_S3_BUCKET: {{ .Values.secret.data.AWS_S3_BUCKET | quote }}
{{- end }}
