apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecms.fullname" . }}-api
  labels:
    {{- include "ecms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
